### PR TITLE
Updated CSS and Responsiveness - Job Posting and Job Postings Summary

### LINKED ISSUE #47: As a user I want to view the website in different screen sizes so that I can access it using different devices.
USP : 5
Priority : 1
Description: The user should be able to view the website in different devices such as desktop, laptop, tablet and mobile and the application should be responsive to these devices.

### LINKED ISSUE #218: Enhancement : Fix spacing between the fields in job posting page
Fix the spacing between each input in the job posting page

### LINKED ISSUE #219: Enhancement : Job summary page CSS fixes
- Center the page title 
- Reduce the distance between the "Edit" and "Delete" button.

### LINKED ISSUE #220: Enhancement : Confirmation when deleting a job
Allow user to have a confirmation before deleting a job.

### PR DESCRIPTION
**Pull request by Itsmeeeet**
### Job Posting and Job Postings Summary

1. **Job Posting page**

- Updated CSS and made responsive for mobile, laptop and larger devices.
-  Removed the unwanted buttons.

Screenshot 2023-04-14 at 9 53 20 PM

Screenshot 2023-04-14 at 9 52 51 PM

Screenshot 2023-04-14 at 9 52 36 PM

Screenshot 2023-04-14 at 9 49 28 PM

2. **Job Posting Summary Page**

- Updated CSS with a better table view
- Made responsive for mobile, laptop and other larger devices.
- For mobile devices there is horizontal scroll for the table keeping the Job Title fixed at one place.

Screenshot 2023-04-14 at 9 55 14 PM

Screenshot 2023-04-14 at 9 54 52 PM

- In horizontal scroll Job Title column remains fixed.

Screenshot 2023-04-14 at 9 54 34 PM

Screenshot 2023-04-14 at 9 53 40 PM

### CODE REVIEW

**Review by imran1289-ah — APPROVED** [review]
Eveything seems good, but i noticed something. Is this scroll button normal? can you remove it . if possible
image

**Comment by Itsmeeeet** [comment]
Added Delete Confirmation box :

Screenshot 2023-04-17 at 3 45 44 PM
Screenshot 2023-04-17 at 3 45 55 PM
Screenshot 2023-04-17 at 3 46 06 PM

And also fixed the scrollbar of JobPosting page

**Review by imran1289-ah — APPROVED** [review]
Seems good, Only need to 1) First Fix the conflicts, then 2) Add translation in i18next for the delete confirmation

**Comment by Aboudik1452** [comment]
Here are my comments regarding the conflicts:

In regards to the JobList page, the CSS change was made to prevent the footer from always being visible at the bottom of the browser window. I think it would be better to have the footer at the very bottom of the page.

Here's what I mean. The first gif demonstrates your changes made.
firefox_MUQrsyuYdA

See how the footer is always visible in the browser window? The following gif demonstrates my CSS changes.

brave_IhBupcNNCN

To make my trick work, I had to include the Navbar and the Footer inside the component `JobList.jsx`. The conflict is due to the **following image**
image

I added a new div that takes care of the page height, and the navbar at the very top. I also created a new CSS file for the LoginFooter `loginfooter.module.css` and for this page `JobList.module.css` which are currently being used in `dev_new`. Thus, the class names were modified to retrieve the name from the module file.

To solve this conflict, you can either do the following:
- Accept incoming change (JobList code from dev_new), and move your CSS fixes into the module file included in dev_new. You can simply move your css code into the css module file. I changed pageTitle to title, you can revert that change.
- Accept current changes (JobList code from your branch), and add the navbar and footer of JobList back to `App.jsx`, which were removed to make my trick work.

I hope this was helpful. Let me know if you have more questions 🙂

**Comment by imran1289-ah** [comment]
Accept your changes as the navbar and footer was added to this job in PR #222

**Pull request merged**
